name: Test Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the listed branches
  push:
    branches: [ main ]
    paths-ignore: # ignore push events to paths matching the following patterns
      - '**.md'
  #      - '.github/workflows/*yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rubocop_and_tests:
    name: Rubocop and RSpec
    runs-on: ubuntu-latest # https://github.com/actions/runner-images#available-images
    env:
      BUNDLE_CACHE_PATH: "/bundle_cache-goodnight_app"
      POSTGRES_VOLUME: "/db-goodnight_app"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_pass"
      POSTGRES_PORT: "5432"
      RAILS_ENV: "test"

    steps:
      - name: Check out the code from the repo
        uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Setup DB
        run: docker exec goodnight_app ./bin/setup

      - name: Rubocop
        run: docker exec goodnight_app bash -c "bundle exec rubocop -P"

      - name: RSpec tests
        run: docker exec goodnight_app bash -c "RAILS_ENV=test bundle exec rspec"